#!/bin/sh
#
# bspwm: external_rules_command

id=${1?};
instance=$3;
class=$2;

case $class in
	(Gimp*) echo follow=on;;
	(Gitk) echo state=floating\ layer=normal;;
	(MPlayer) echo state=floating\ layer=normal;;
	(XCalc) echo state=floating\ layer=normal;;
	(Xmessage) echo state=floating\ layer=normal;;
	([lL]ibre[oO]ffice*) echo state=tiled\ layer=normal;;
	(mpv) echo state=floating\ layer=normal;;
esac;
#FLOATING_DESKTOP_ID=$(bspc query -D -d '^13')
#desk_id=$(bspc query -D -d "${5:-focused}")

#[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && echo "state=floating"
