#!/bin/sh
xrandr --output VGA-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-D-0 --off --output HDMI-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-D-1 --off

bspc monitor VGA-1 -d 1 2 3 4 5 
bspc monitor HDMI-1 -d  A B C D E F G


bspc config border_width         2
bspc config window_gap           8
bspc config focused_border_color \#fa0000

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config external_rules_command "/home/ray/.config/bspwm/scripts/bspwm-rules";
bspc config external_rules_command "/home/ray/.config/bspwm/scripts/float.sh";

bspc rule -a Gimp desktop='^7' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Vivaldi-snapshot desktop='^6'
#bspc rule -a caprine desktop='^11'
#bspc rule -a discord desktop='^11'
#bspc rule -a telegram-desktop desktop='^11'
#bspc rule -a slack desktop='^11'
#bspc rule -a "termite -e gotop" desktop = '^1'
#bspc rule -a "termite -e nload wlp0s20f0u2" desktop = '^1'
#bspc rule -a "termite -e sudo iftop -i wlp0s20f0u2" desktop = '^1'
bspc rule -a "[Ss]potify"  desktop = '^9'
#bspc rule -a Hexchat = '^13'
#bspc rule -a ICE-SSB-whatsapp desktop = '^11'
#bspc rule -a ICE-SSB-evernote desktop = '^12'
#bspc rule -a todoist desktop = '^12'
bspc rule -a Station desktop = '^12'

bspc rule -a Ulauncher border=off

$HOME/.config/bspwm/autostart.sh
$HOME/.config/polybar/launch.sh

